export enum ICONS {
    PROFILE = 'profile',
    CLOCK = 'clock',
    HOME = 'home',
    LIST = 'list',
    CLEAR = 'clear',
    FACE_ID = 'face-id',
    EYE = 'eye',
    FINGERPRINT = 'fingerprint',
    LOCATION = 'location',
    LOCK = 'lock',
    LOGOUT = 'logout',
    MAIL = 'mail',
    REFERRAL_CODE = 'referal-code',
    TIENNGAY = 'tienngay',
    CARD = 'card',
    RIGHT_ARROW = 'right-arrow',
    RIGHT_DOWN = 'down-arrow',
    SEARCH = 'search',
    CLOUD = 'cloud',
    PHONE = 'phone',
    USER = 'user',
    ARROWS = 'arrows',
    MONEY = 'money',
    COMPANY = 'ic_company'
}
