require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'Tienngay' do
  config = use_native_modules!
#   config = use_frameworks! :linkage => :static

  # $RNFirebaseAnalyticsWithoutAdIdSupport=true
  $RNFirebaseAsStaticFramework=true

  use_react_native!(:path => config[:reactNativePath],:hermes_enabled => false)

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  permissions_path = '../node_modules/react-native-permissions/ios'
     pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
     pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"
     pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
     pod 'GoogleSignIn'
     pod 'BEMCheckBox'
    #  pod 'Firebase/Analytics', :modular_headers => true
     pod 'GoogleUtilities', :modular_headers => true
    
 pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
 post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            end
        end
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    # installer.pods_project.targets.each do |target|
    #     target.build_configurations.each do |config|
    #       config.build_settings['ENABLE_BITCODE'] = 'NO'
    #     end
    # end
 end
 
end

